Add biocViews keyword to description.
Installation with `install_github` fails with 

```
ERROR: dependency ‘Biobase’ is not available for package ‘BisqueRNA’
```

Adding the `biocViews` keyword to the DESCRIPTION should fix that, since it tells remotes/devtools to also search Bioconductor.